
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeDatabase;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;

import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DHANUSH
 */
public class EmployeeDatabase extends javax.swing.JFrame {

    
   Connection conn=null;
   PreparedStatement pst=null;
   ResultSet rs=null;
   DefaultTableModel mode1=new DefaultTableModel();
    public EmployeeDatabase() {
        initComponents();
        
        Object col[]={"EmpID","Firstname","Surname","Gender","DoB","Age","Salary"};
        mode1.setColumnIdentifiers(col);
        jTable1.setModel(mode1);
        conn=EmployeeDatabase.ConnectDb();
        updateTable();
    }

    
     public static Connection ConnectDb(){
        try
        {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:Employee.db");
            return conn;
            
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null, e);
          return null;
        }
    }
     
            
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnExit = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbtnAddData = new java.awt.Button();
        jbtnPrint = new java.awt.Button();
        jbtnClearData = new java.awt.Button();
        jtxtSurname = new javax.swing.JTextField();
        jtxtGender = new javax.swing.JTextField();
        jtxtDob = new javax.swing.JTextField();
        jtxtAge = new javax.swing.JTextField();
        jtxtEmployeeID = new javax.swing.JTextField();
        jtxtSalary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel1.setText("Salary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jbtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnExit.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jbtnExit.setLabel("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 160, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Firstname", "Surname", "Gender", "DOB", "Age", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 640, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel2.setText("Firstname");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel3.setText("Surname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setText("Employee Database Management System");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 590, -1));

        jtxtFirstname.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jtxtFirstname.setText("   ");
        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 180, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jbtnAddData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnAddData.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jbtnAddData.setLabel("Add");
        jbtnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 160, -1));

        jbtnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnPrint.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jbtnPrint.setLabel("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 160, -1));

        jbtnClearData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnClearData.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jbtnClearData.setLabel("Clear Data");
        jbtnClearData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClearData, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, 160, -1));

        jtxtSurname.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jtxtSurname.setText("   ");
        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 180, -1));

        jtxtGender.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jtxtGender.setText("   ");
        jtxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGenderActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 180, -1));

        jtxtDob.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jtxtDob.setText("   ");
        jtxtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDobActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 180, -1));

        jtxtAge.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jtxtAge.setText("   ");
        jtxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAgeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 180, -1));

        jtxtEmployeeID.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jtxtEmployeeID.setText("   ");
        jtxtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmployeeIDActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 180, -1));

        jtxtSalary.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jtxtSalary.setText("   ");
        jtxtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 180, -1));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 29)); // NOI18N
        jLabel8.setText("Employee ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jDelete.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 110, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\DHANUSH\\Documents\\NetBeansProjects\\EmployeeDatabase\\img\\mastercard-logo.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 280, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
   
    
    
    
    
    
    
    
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
              frame=new JFrame("Exit");
              if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Employee Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
                  System.exit(0);
              }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnClearDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearDataActionPerformed
     jtxtEmployeeID.setText(null);
     jtxtFirstname.setText(null);
     jtxtSurname.setText(null);
     jtxtGender.setText(null);
     jtxtDob.setText(null);
     jtxtAge.setText(null);
     jtxtSalary.setText(null);
     
    }//GEN-LAST:event_jbtnClearDataActionPerformed
//{EmpID,Firstname,Surname,Gender,DoB,Age,Salary}dhnush $hsdhanushdh 
  //conn.db to disticnt the ten jdbc server D.thg
    //med the the man to intervene the impirtant the adate so i will bedo conn mann the entire way to engulf the ,an the 
    //i will pst.setsrring
    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstnameActionPerformed

    private void jbtnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddDataActionPerformed
         String sql="INSERT INTO Employee(EmpID,Firstname,Surname,Gender,DoB,Age,Salary)VALUES(?,?,?,?,?,?,?)";
         try
         {
             pst=conn.prepareStatement(sql);
             pst.setString(1, jtxtEmployeeID.getText());
             pst.setString(2, jtxtFirstname.getText());
             pst.setString(3,jtxtSurname.getText());
             pst.setString(4,jtxtGender.getText());
             pst.setString(5,jtxtDob.getText());
             pst.setString(6,jtxtAge.getText());
             pst.setString(7,jtxtSalary.getText());
         pst.execute();
         JOptionPane.showMessageDialog(null,"System Update Completed");
         rs.close();
         pst.close();
         }
         
         catch(Exception e)
         {
              JOptionPane.showMessageDialog(null,e);
         }
         
         updateTable();
    }//GEN-LAST:event_jbtnAddDataActionPerformed

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurnameActionPerformed

    private void jtxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGenderActionPerformed

    private void jtxtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDobActionPerformed

    private void jtxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAgeActionPerformed

    private void jtxtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSalaryActionPerformed

    private void jtxtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmployeeIDActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
         MessageFormat header=new MessageFormat("Printing in progress");
         MessageFormat footer =new MessageFormat("Page {0,number,interger}");
         try
         {
             jTable1.print(JTable.PrintMode.NORMAL,header,footer);
         }
         catch(Exception e)
         {
             System.err.format("No Printer  Found", e.getMessage());
         }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        int p=JOptionPane.showConfirmDialog(null,"Are You Sure","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql="delete from Employee where EmpID=?";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1,jtxtEmployeeID.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted");
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            updateTable();
        }
        
    }//GEN-LAST:event_jDeleteActionPerformed

    public void updateTable(){
        conn =EmployeeDatabase.ConnectDb();
        if(conn!=null)
        {
            String sql="Select EmpID,Firstname,Surname,Gender,DoB,Age,Salary from Employee";
            try
            {
             pst=conn.prepareStatement(sql);
             rs=pst.executeQuery();
             Object[] columnData=new Object[8];
             while(rs.next()){
                 columnData[0]=rs.getString("EmpID");
                 columnData[1]=rs.getString("Firstname");
                 columnData[2]=rs.getString("Surname");
                 columnData[3]=rs.getString("Gender");
                 columnData[4]=rs.getString("DoB");
                 columnData[5]=rs.getString("Age");
                 columnData[6]=rs.getString("Salary");
                  mode1.addRow(columnData);  
                  
             }
            }
            catch(Exception e)
            {
                            JOptionPane.showMessageDialog(null,e);
  
            }
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Button jbtnAddData;
    private java.awt.Button jbtnClearData;
    private java.awt.Button jbtnExit;
    private java.awt.Button jbtnPrint;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtDob;
    private javax.swing.JTextField jtxtEmployeeID;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtGender;
    private javax.swing.JTextField jtxtSalary;
    private javax.swing.JTextField jtxtSurname;
    // End of variables declaration//GEN-END:variables
}
